### ISSUE TITLE
Not able to see Karate Runner Tests using Karate Runner

### ISSUE THREAD

**Issue by varunpatil03** [kirksl/karate-runner#39] opened 2020-04-28 04:26 UTC
Not able to run Karate Tests using Karate Runner
`[ERROR] No plugin found for prefix '.options=c' in the current project and in the plugin groups`

**Comment by kirksl** [comment] 2020-04-28 05:59
@varunpatil03 can you please describe the steps to reproduce this.  it sounds like a possible build configuration issue in maven or gradle

**Comment by varunpatil03** [comment] 2020-04-28 17:39
Thanks for looking into this issue. Below is the pom I am using. Also, my work space has 2  maven projects. The one used for testing I am adding here. Can you please check.
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>****.itsuppt.automation.wls.modules</groupId>
    <artifactId>paas-springboot-starter-int-test</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.12</java.version>
        <maven.compiler.version>3.6.0</maven.compiler.version>
        <maven.surefire.version>2.19.1</maven.surefire.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit4</artifactId>
            <version>${maven.surefire.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-cucumber</artifactId>
            <version>4.0.6</version>
        </dependency>

        <dependency>
            <groupId>com.intuit.karate</groupId>
            <artifactId>karate-gatling</artifactId>
            <version>0.9.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.influxdb</groupId>
            <artifactId>influxdb-java</artifactId>
            <version>2.12</version>
        </dependency>
        <dependency>
            <groupId>****.itsuppt.automation.wls.modules</groupId>
            <artifactId>****-api-test-core</artifactId>
            <version>1.2-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        

        

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.8</version>
                <configuration>
                    <argLine>-Dfile.encoding=UTF-8</argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <compilerArgument>-Werror</compilerArgument>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-maven-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <simulationsFolder>src/test/java</simulationsFolder>
                    <includes>
                        <include>performance.PerformanceRunner</include>
                    </includes>
                    <configFolder>src/test/resources</configFolder>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.properties</include>
                </includes>
                <excludes>
                    <exclude>**/*.exe</exclude>
                </excludes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>**/*.properties</exclude>
                </excludes>
            </resource>
        </resources>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>2.7</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>project-team</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>
</project>`

**Comment by kirksl** [comment] 2020-04-28 19:16
@varunpatil03 i don't think this is a "karate runner" issue?  it appears to be a build system issue that you need to solve for maven.  i would suggest creating a pom.xml for maven via the steps here https://github.com/intuit/karate#quickstart or looking at examples within the karate github project eg https://github.com/intuit/karate/blob/master/karate-demo/pom.xml

closing this for now but please reopen if this is truly a problem with the VSCode karate runner plugin.

**Closed by kirksl** 2020-04-28 19:16 UTC
Labels: investigating

**Comment by hahampis** [comment] 2020-10-05 13:05
@kirksl I have the same problem. I am on Windows, karate 0.9.3, karate-runner 0.9.3 using maven. The extension attempts to run the command:
`mvn test -f "c:\Users\hahampis\Github\path\to\pom\pom.xml" -Dtest=Path_to/My_Runner -Dkarate.options="c:\Users\hahampis\Github\path\to\my\feature\MyFeature.feature"`

and I get:

`[ERROR] No plugin found for prefix '.options=c' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] 
available from the repositories`

It has something to do with the path and being on Windows... If I run `mvn test`  from the project root (containing the pom.xml) surrounding the whole `-Dkarate.options` in double quotes and using relative paths:
`mvn test  -Dtest=Path_to/My_Runner "-Dkarate.options=classpath:path\to\my\feature\MyFeature.feature"`

then it works.

**Comment by kirksl** [comment] 2020-10-05 18:22
@hahampis can you try again with...
karate 0.9.6 and see if that solves the problem.

if still an issue can you verify the sample karate project here works on your machine (defaults to maven)...
i see errors when switching this project back to 0.9.3 and know karate has made fixes regarding paths so i would advise upgrading to a newer version than 0.9.3
https://github.com/kirksl/karate-maven-gradle

the only other thing i can think of is maybe spaces are your file path which i'd advise against.

**Comment by hahampis** [comment] 2020-10-06 06:45
@kirksl thank you for your answer. Unfortunately the same error happens in the sample project. I don't have spaces in my file path...
It's okay, no big deal, just a shame I can't use this awesome feature to run karate tests!

**Comment by kirksl** [comment] 2020-10-06 16:12
@hahampis this sounds like an issue with your environment.  possibly versions you are using locally for some tools.  i'd suggest trying to use the version of maven included with the sample project.  you can try this by turning on the maven wrapper in karate settings.  see image below.  and or try running a similar command as i just did below from the sample project's root folder.

this works for me
mvnw clean test -f "c:\projects\karate-maven-gradle\pom.xml" -Dtest=OrderRunner -Dkarate.options="c:\projects\karate-maven-gradle\src\test\java\org\company\order.feature"

![image](https://user-images.githubusercontent.com/24948266/95228364-14d5dd80-07b4-11eb-9102-68a1959ce80f.png)

**Comment by hahampis** [comment] 2020-10-07 06:49
@kirksl I tried using the wrapper, same result. I uninstalled my version of maven (downloaded through scoop package manager) and reinstalled it from the official .zip archive. Same results. 
In any case, I can always fix it changing the quotes to include `-Dkarate.options`. For example with your command, If I run it this way:
mvnw clean test -f "c:\projects\karate-maven-gradle\pom.xml" -Dtest=OrderRunner **"**-Dkarate.options=c:\projects\karate-maven-gradle\src\test\java\org\company\order.feature"
it works. This is how it is done also in the examples of the [Karate documentation](https://github.com/intuit/karate#command-line)...

**Comment by kirksl** [comment] 2020-10-07 20:13
@hahampis sorry to hear this is still not working for you.  i'm happy to continue debugging this issue with you if you are interested.  i'd also like to find good documentation backing up how good support is when using quotes this way.  if it could be proven that maven supports this across many versions and it can be documented here i might be comfortable changing the plugin to enforce quotes this way.  at least temporarily, meaning we'd make that single change and make sure it didn't break a lot of users all of a sudden.

**Comment by hahampis** [comment] 2020-10-08 06:13
@kirksl sure, let's continue debugging! Let me know what I can do to help.

**Comment by kirksl** [comment] 2020-10-08 19:34
@hahampis great.  i have a couple ideas.  for all of them i'd like to use the sample project i mentioned earlier as i know that works and i can test with it on my end at the same time that you do.
https://github.com/kirksl/karate-maven-gradle

first thing i'm wondering is it possible to do a clean install of vscode and karate runner extension?  meaning uninstall vscode, delete all of the extensions you previously installed from your login profile at a path similar to mine (C:\Users\Kirk\.vscode\extensions), install the latest vscode, install only the karate runner extension(maybe the "java extension pack" if needed) and to try the sample project again.

second, if still problems after trying the first option above.   is it possible for you to try all of this on another machine?  because it's still failing for you with this sample project it seems like there is a difference with your computer versus mine so i think that would be a quick way to isolate the problem to the current machine you are on.

third if the problem still occurs can you collect as much information for me such as what versions of windows you are using, any software you've installed that you suspect might interfere with maven.  i don't know what software that might be so you might want to compare what you have installed on windows and search online to see if it can cause trouble.  really doubtful this would happen, but running out of options to try.

also want to point out that i just had someone report a bug that running maven with quotes around the -D option actually fails for them so something interesting is going on that i'd like to track down.   https://github.com/kirksl/karate-runner/issues/66
