### ISSUE TITLE
Karate-Runner overides another useful plugin

### ISSUE THREAD

**Issue by blaisn** [kirksl/karate-runner#62] opened 2020-08-28 00:56 UTC
Karate-Runner overides "Cucomber (Gherkin) file support" VSCode plugin. The latter being very useful for syntax highlighting and auto-indentation. Since Karate-Runner only sytax highlight, I would prefer to keep the other one for this task and Karate-Runner to run/debug tests.
Is it possible to cancel the overide? Or include auto-indentation in Karate-Runner?

**Comment by kirksl** [comment] 2020-08-28 16:27
@blaisn we looked into this previously and at that time there was no way to turn off syntax highlighting without removing the Karate Language from the plugin.  we will explore this again as the VSCode API is constantly evolving.  can you provide an example of what you are looking for with auto-indentation.

**Comment by blaisn** [comment] 2020-08-28 21:11
As I said, the VSCode plugin "Cucumber (Gherkin) Full Support" 
https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete
does the trick with its default settings. For example, this extract was entered without indentation and upon saving, it was neatly auto-indented:
`Feature: Suite de tests pour api GET unité recherche avancée (champ code)

    Background:
        Given url url_v1

    Scenario: GET unite

        Given path 'unite'
        And param code = '0102'
        And param limit = 2
        When method get
        Then status 200
        And match each response[*].code == '0102'

    Scenario: GET unité recherche

        Given path 'unite'
        And param code[EQ] = '0102'
        And param limit = 2
        When method get
        Then status 200
        And match each response[*].code == '0102'`

**Comment by kirksl** [comment] 2020-08-29 17:50
i couldn't reproduce this problem.

can you clarify your steps to reproduce this including version numbers of VSCode and the extensions.
i uninstalled Karate Runner and the Cucumber extension still doesn't auto indent for me.  i'm using the latest versions of VSCode and extensions.

**Comment by kirksl** [comment] 2020-08-31 00:47
@blaisn closing this issue as i've tested Karate Runner with other extensions and auto indentation still works.  i suspect the extension you referenced to auto-indent might be having trouble with indenting as it never worked for me regardless of having Karate Runner extension installed.

here is an extension that did work to auto-indent gherkin regardless of Karate Runner installed or uninstalled
https://marketplace.visualstudio.com/items?itemName=siarheikuchuk.gherkin-beautifier-vs-code-plugin

**Closed by kirksl** 2020-08-31 00:47 UTC
Labels: investigating
