### ISSUE TITLE
VS Code karate config js error while running scenario with java 1.8 and karate zip release version 1.2.0.RC1

### ISSUE THREAD

**Issue by smtripathi99** [kirksl/karate-runner#141] opened 2022-04-15 13:59 UTC
I am getting following error while running a scenario file from VS Code 1.53.2 with Java 1.8 and karate version 1.2.0.RC1, Windows 10 64 bit:

ERROR com.intuit.karate - src/test/java/feature/FOC.feature:5
  * url baseUrl
  js failed:

 01: baseUrl

   org.graalvm.polyglot.PolyglotException: ReferenceError: "baseUrl" is not defined
   - <js>.:program(Unnamed:1)

karate-config.js file:

```
function fn() {
       var env = karate.env; // get system property 'karate.env'
     karate.log('karate.env system property was:', env);
     if (!env) {
        env = 'qa';
    }
    var config = {
        secretKey: 'ssshhhhhhhhhhh!!!!',
        // myVarName: 'someValue'
    }
    if (env == 'dev') {
        config.baseUrl = 'https://services-dev.com/'
 
    } else if (env == 'qa') {
        config.baseUrl = 'https://services-qa.com/'
 
    }
    var result = karate.callSingle('classpath:tlrservice/feature/tripIdGenaration.feature');
    config.tripIdGenaration = result;
    return config;
  }
```

feature file:

```
Feature: Test

  Background:
    * url baseUrl
```

**Comment by kirksl** [comment] 2022-04-20 23:22
@smtripathi99 I can't reproduce this.  I downloaded the same Zip Release and added a karate-config and feature file both shown in the screenshot.  I am using VSCode 1.66.2.  Can you try again?
![image](https://user-images.githubusercontent.com/24948266/164340448-12e640b0-6730-4a27-8cd8-534edf0309e7.png)

**Comment by kirksl** [comment] 2022-04-25 17:08
@smtripathi99 Closing this for now.  Please open a new ticket if this is still an issue.

**Closed by kirksl** 2022-04-25 17:08 UTC
Labels: investigating
