### ISSUE TITLE
VSCode debugger hangs after first iteration in Scenario Outline

### ISSUE THREAD

**Issue by workwithprashant** [kirksl/karate-runner#121] opened 2021-10-25 16:06 UTC
**Environment**:
Karate Runner v1.1.1
VSCode: 1.61.2

1. Download sample [project](https://github.com/workwithprashant/poc-karate-debug/tree/bugfix/vscode_debug_scenario_outline_stuck_after_first_iteration)
2. Put breakpoint in [users.feature](https://github.com/workwithprashant/poc-karate-debug/blob/bugfix/vscode_debug_scenario_outline_stuck_after_first_iteration/src/test/java/examples/users.feature#L11)
3. Start debugging in VSCode and try to step over after first iteration
4. Test execution hangs after first iteration in scenario outline

**Observations**:
- Tried with Karate 1.1.0, 1.2.0.RC1 and also latest develop branch build; issue still persist
- Issue does not occur when [generic_functions.feature](https://github.com/workwithprashant/poc-karate-debug/blob/bugfix/vscode_debug_scenario_outline_stuck_after_first_iteration/src/test/java/karate-config.js#L4) has empty [background](https://github.com/workwithprashant/poc-karate-debug/blob/bugfix/vscode_debug_scenario_outline_stuck_after_first_iteration/src/test/java/examples/generic_functions.feature#L8)

**Comment by kirksl** [comment] 2022-01-02 01:57
@workwithprashant i am unable to reproduce this issue using your repro steps.  using your project without any changes, on windows 10, vscode 1.63.1.  please let us know if this is still an issue for you.

https://recordit.co/UE57nb5Faq

**Comment by workwithprashant** [comment] 2022-01-04 19:44
@kirksl As mentioned in my previous [reply ](https://github.com/kirksl/karate-runner/issues/121#issuecomment-951927668), it started working only after changing from `karate.call` to `karate.callSingle`. If you change back `karate.callSingle` to `karate.call`, you will be able to reproduce the issue as shown in following video recording.

**Environment**:
Windows 10
VSCode 1.63.2

https://recordit.co/f2h1XasaOO

**Comment by kirksl** [comment] 2022-01-04 20:47
@workwithprashant thanks for the re-clarification.  this issue is happening on the command line when not using karate runner extension.  because of that this looks external and related to karate.  closing here, but please open in the karatelabs repo.

**Closed by kirksl** 2022-01-04 20:47 UTC
Labels: no repro

**Comment by workwithprashant** [comment] 2022-01-04 21:31
@kirksl Sorry, I am confused. I am using `Karate: Debug` and not using command line anywhere (followed the similar steps as your vide) . Please let me know how did you determine that the issue is happening on the command line.

**Comment by kirksl** [comment] 2022-01-04 22:29
@workwithprashant i started my own debug adapter and issued the same commands that the vscode ide does via its base protocol as described here https://microsoft.github.io/debug-adapter-protocol/overview.  This removed vscode and karate runner from the repro.  my thoughts are implementation on the karate side communicating back to the debug adapter has an issue.
