### ISSUE TITLE
Unable to use Runner on Windows

### ISSUE THREAD

**Issue by impos89** [kirksl/karate-runner#43] opened 2020-05-02 21:40 UTC
Hi,

I tried to configure both debugger and Runner for my project. Debugger works fine, but when i try to use runner, then I see it does not take feature/scenario path
![image](https://user-images.githubusercontent.com/6552297/80892844-82de1c00-8ccd-11ea-8ad5-cb8c97e53608.png)
As you could see in attached screen the path is added, but test was not executed. When i tried to run this command manually i got same result, but when i added quotation marks, then test started correctly.

Here is working execution example when i added quotation marks manually:
![image](https://user-images.githubusercontent.com/6552297/80892920-1f082300-8cce-11ea-9b26-405dcc877723.png)

I didn't found any option to enrich runner parameters to add quotation marks, so i suppose it can be considered as a bug.

**Comment by impos89** [comment] 2020-05-02 21:43
OS: Windows 10

**Comment by kirksl** [comment] 2020-05-03 01:19
@impos89 can you try putting double quotes around your classpath.  i know windows and cmd.exe don't work well with single quotes.
![image](https://user-images.githubusercontent.com/24948266/80896257-7774fb80-8ca1-11ea-8161-809b20768a8c.png)

**Comment by impos89** [comment] 2020-05-03 17:31
I checked it and it didn't helped. 
Probably I could try changing terminal to wsl, but it's just a workaround. Thing that helped me was putting parameters to feature file in question marks.

Btw. What happen in situation when parameter has a space in directory name ? In that case parameter should be put between question marks to be considered as a single path.

**Comment by kirksl** [comment] 2020-05-04 03:01
your point is valid for paths with spaces.  it would be a good idea to wrap the path in quotes.  ill look into that to make sure it will consistently work on macos, linux and debug configurations.  im still curious why this is not working for you as we have thousands of people running without problems.  if you happen to have a sample project reproducing the problem and any other details that might help figure out the reasons.  one thing i can see but doubt it's a problem is your decimal separator is a comma, not a period.  i guess maybe another setting tied to the region you have Windows 10 set to could be something interesting?  also curious what versions you are using for vscode, node, Java, etc

**Comment by kirksl** [comment] 2020-05-04 18:16
@impos89 this should be fixed.  looks like we were putting double quotes around the feature file and path for maven, gradle, but hadn't done it for the Karate Jar option yet.  please verify and let us know if this issue is not resolved.  https://github.com/kirksl/karate-runner/commit/3cf730bd6d38226dcac328e69bb42be56e6d2a97

**Closed by kirksl** 2020-05-04 18:16 UTC
Labels: investigating
